### ISSUE TITLE
Pointcloud units not in SI?

### ISSUE THREAD

**Issue by ruffsl** [PercATI/RealSense-ROS#1]
From what I gathered from just trying out this ROS driver for the r200, I'm relizing the pointclouds are not published in SI units (i.e. meters). I'd propose using the standered SI like most 3D sensors.

See *bannana* for scale (the little grid in the bottom right is 10x10 meters):
![screenshot from 2015-08-25 16 25 58](https://cloud.githubusercontent.com/assets/2293573/9478472/278235f8-4b46-11e5-945a-27d3e9cd433b.png)

**Comment by PercATI** [comment]
Hi, 

You are right. Currently the default output is in centimeters. 
In the launchfile you can set the pcScale to 1000 to get it in meters.

Try:
roslaunch realsenes realsense_r200_launch.launch pcScale:=1000

Thanks,
Amit

**Comment by ruffsl** [comment]
I think others may agree that point clouds should not need to be scaled, and exposing this permater to users may lead to confusion and unforseen errors. We should follow this REP:
http://www.ros.org/reps/rep-0103.html

**Comment by PercATI** [comment]
Got it.
I changed the default pcScale to 1000 to void confusion. 

Thanks for the feedback!
Amit
