### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by nh2** [PercATI/RealSense-ROS#5]
Hey,

I'm trying to understand where's what in this driver, but somehow I can only find header files.

Where's the implementation?

**Comment by PercATI** [comment]
Currently, we are only providing binary version of our libraries.

**Comment by nh2** [comment]
Ah, I see. May I ask what the reason for it is, or whether you have plans to open-source it in the future?

Thank you!

**Comment by PercATI** [comment]
In near future, we may plan to provide the source code - after it goes thru internal approval process

**Comment by nh2** [comment]
OK, thank you very much.
